"""users added

Revision ID: 75943997f91d
Revises: cbb53a4b2f8f
Create Date: 2021-03-25 10:53:58.262859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75943997f91d'
down_revision = 'cbb53a4b2f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_column('Posts', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Posts', 'userid')
    # ### end Alembic commands ###
